### PR TITLE
fix websockets ping/pong control frames handling

### LINKED ISSUE #700: Unhandled pong from IE11 causes connection to die
Issue: IE11 sends a pong every 30 seconds which is unhandled and eventually the application tries to decode the pong frame and fails. This kills the connection from ie11 to the server. 

Simple demo app to reproduce the issue:
https://github.com/jeisea/violet-demo
Node web app. 

Spring boot rsocket server in the zip.

### PR DESCRIPTION
**Pull request by mostroverkhov**
closes #700

### CODE REVIEW

File: rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java [hunk 1]
```diff
@@ -107,33 +101,7 @@ public static WebsocketServerTransport create(InetSocketAddress address) {
...
-                tcpServer.doOnConnection(
-                    connection ->
-                        connection.addHandlerLast(
-                            new ChannelInboundHandlerAdapter() {
-                              @Override
-                              public void channelRead(ChannelHandlerContext ctx, Object msg)
-                                  throws Exception {
-                                if (msg instanceof PongWebSocketFrame) {
-                                  logger.debug("received WebSocket Pong Frame");
-                                } else if (msg instanceof PingWebSocketFrame) {
```
Comment (yschimke) [inline rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java]: What is handling the incoming Ping frames after this PR?  Surely we still need to respond?

Comment (mostroverkhov) [reply rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java]: pings are handled by reactor-netty https://github.com/reactor/reactor-netty/blob/cbd4c588abfb852931cb81d5a605f9ab5c844595/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java#L147
