### PR TITLE
removes limit rate operator

### LINKED ISSUE #825: Spring Boot 2.3.0.RC1 - RSocket over Websocket transport - requestStream - produces additional request(255)
Had created the issue at Spring Boot, but may be this should be posted here:
https://github.com/spring-projects/spring-boot/issues/21360

With latest 2.3.0.RC1 RSocket "requestStream" started producing additional request to Flux inside controller with quantity 255.

Configuration to reproduce the issue:

Spring Boot 2.3.0.RC1
RSocket plugged to server
Transport - Websockets
Using @MessageMapping controller
RSocket connection with Composite Metadata ('message/x.rsocket.composite-metadata.v0'), Binary MimeType ('application/octet-stream') and Buffer encoders
Tested with javascript RSocket client v0.0.19.

Previous version of Spring Boot 2.3.0.M4 hasn't such issue.

### PR DESCRIPTION
**Pull request by OlegDokuka**
closes #825 

This PR removes usage of `limitRate` operator and provides an example of how one can provide `limitRate` just in case this is crucial

### CODE REVIEW

File: rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+                            .doOnRequest(e -> requests.add("Responder requestN(" + e + ")"))
+                            .map(aLong -> DefaultPayload.create("Interval: " + aLong));
+                      }
+
+                      @Override
+                      public Flux<Payload> requestChannel(Publisher<Payload> payloads) {
+                        return Flux.from(payloads)
+                            .doOnRequest(e -> requests.add("Responder requestN(" + e + ")"));
+                      }
+                    }))
```
Comment (rstoyanchev) [inline rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java:45]: This could be `SocketAcceptors.with(new RSocket() {...})`.

File: rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+        .then()
+        .doFinally(signalType -> socket.dispose())
+        .then()
+        .block();
+
+    requests.forEach(request -> logger.debug("Requested : {}", request));
+  }
+
+  static class LimitRateRSocket extends RSocketProxy {
+
```
Comment (rstoyanchev) [inline rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java:98]: This could look better as a `LimitRateInterceptor` in a top-level class, applying the proxy internally.

Comment (OlegDokuka) [reply rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java]: fixed

File: rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java (hunk 1 above)
Comment (OlegDokuka) [reply rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java]: fixed
