### PR TITLE
RSocketRequester: fix concurrent modification of senders & receivers …

### LINKED ISSUE #679: AssertionError occurred during closing rsocket
Hi, RSocket team!

I noticed that some of my tests fail with this error periodically during clean-up. Unfortunately, I don't have a stable test case to reproduce this. As far as I'm aware, all of the interactions with rsocket are finished by the time I call `dispose()`. Do you have any advice on how I can debug this? 

```
java.lang.AssertionError: null is not a legitimate internal value. Concurrent Modification?
	at io.rsocket.internal.SynchronizedIntObjectHashMap.toExternal(SynchronizedIntObjectHashMap.java:99)
	at io.rsocket.internal.SynchronizedIntObjectHashMap.access$900(SynchronizedIntObjectHashMap.java:38)
	at io.rsocket.internal.SynchronizedIntObjectHashMap$PrimitiveIterator.value(SynchronizedIntObjectHashMap.java:664)
	at io.rsocket.internal.SynchronizedIntObjectHashMap$1$1.next(SynchronizedIntObjectHashMap.java:235)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at io.rsocket.RSocketRequester.terminate(RSocketRequester.java:478)
	at io.rsocket.RSocketRequester.lambda$new$0(RSocketRequester.java:93)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
	at reactor.core.publisher.MonoProcessor$NextInner.onComplete(MonoProcessor.java:592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:380)
	at reactor.core.publisher.MonoProcessor.onComplete(MonoProcessor.java:335)
	at io.rsocket.internal.BaseDuplexConnection.dispose(BaseDuplexConnection.java:23)
	at io.rsocket.internal.ClientServerInputMultiplexer$InternalDuplexConnection.dispose(ClientServerInputMultiplexer.java:205)
	at io.rsocket.RSocketRequester.dispose(RSocketRequester.java:188)
	at io.rsocket.util.RSocketProxy.dispose(RSocketProxy.java:65)
        ...
```

### LINKED ISSUE #686: REJECTED_SETUP sometimes produces Exceptions$ReactiveException instead of RejectedSetupException
Sometimes when an exception occurs in `SocketAcceptor` the Exception is `RejectedSetupException` (expected). However, it appears about 10% of the time the error is `Exceptions$ReactiveException: java.lang.Throwable: closed connection` (not expected). A complete stacktrace can be found below:

```
reactor.core.Exceptions$ReactiveException: java.lang.Throwable: closed connection
	at reactor.core.Exceptions.propagate(Exceptions.java:326)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1514)
	at org.springframework.security.rsocket.itests.ConnectionRejected.lambda$acceptorExceptionTest$3(ConnectionRejected.java:59)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:786)
	at org.assertj.core.api.AssertionsForClassTypes.assertThatCode(AssertionsForClassTypes.java:757)
	at org.assertj.core.api.Assertions.assertThatCode(Assertions.java:1171)
	at org.springframework.security.rsocket.itests.ConnectionRejected.acceptorExceptionTest(ConnectionRejected.java:51)
	at org.springframework.security.rsocket.itests.ConnectionRejected.thisWillFail(ConnectionRejected.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)


	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		... 30 more
Caused by: java.lang.Throwable: closed connection
	at io.rsocket.RSocketRequester.lambda$handleSendProcessorCancel$2(RSocketRequester.java:148)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.rsocket.RSocketRequester.handleSendProcessorCancel(RSocketRequester.java:145)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
	at reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:243)
	at reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:92)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1156)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:758)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:734)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:605)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:621)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:605)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:467)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:968)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:231)
	at reactor.netty.DisposableChannel.dispose(DisposableChannel.java:74)
	at reactor.netty.channel.ChannelOperations.dispose(ChannelOperations.java:162)
	at io.rsocket.transport.netty.TcpDuplexConnection.doOnClose(TcpDuplexConnection.java:68)
	at io.rsocket.internal.BaseDuplexConnection.lambda$new$0(BaseDuplexConnection.java:11)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
	at reactor.core.publisher.MonoProcessor$NextInner.onComplete(MonoProcessor.java:517)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:307)
	at reactor.core.publisher.MonoProcessor.onComplete(MonoProcessor.java:264)
	at io.rsocket.internal.BaseDuplexConnection.dispose(BaseDuplexConnection.java:23)
	at io.rsocket.internal.ClientServerInputMultiplexer$InternalDuplexConnection.dispose(ClientServerInputMultiplexer.java:205)
	at io.rsocket.RSocketRequester.handleStreamZero(RSocketRequester.java:531)
	at io.rsocket.RSocketRequester.handleIncomingFrames(RSocketRequester.java:514)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.subscribe(FluxGroupBy.java:696)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8056)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1582)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:316)
	at io.rsocket.internal.ClientServerInputMultiplexer.lambda$new$1(ClientServerInputMultiplexer.java:116)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:380)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:316)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:201)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:342)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

A test to reproduce the issue can be found below:

```java

import io.rsocket.*;
import io.rsocket.exceptions.RejectedSetupException;
import io.rsocket.transport.netty.client.*;
import io.rsocket.transport.netty.server.*;
import io.rsocket.util.DefaultPayload;
import org.junit.Test;
import reactor.core.publisher.Mono;

import java.net.InetSocketAddress;

import static org.assertj.core.api.Assertions.assertThatCode;

public class ConnectionRejected {

	@Test
	public void thisWillFail() {
		for (int i=1;i <= 1000;i++) {
			acceptorExceptionTest();
		}
	}

	@Test
	public void thisFailsSometimes() {
		acceptorExceptionTest();
	}

	private void acceptorExceptionTest() {
		CloseableChannel server = RSocketFactory.receive()
			.acceptor(((setup, sendingSocket) -> Mono.error(() -> new RuntimeException("Ooops"))))
			.transport(TcpServerTransport.create("localhost", 0))
			.start()
			.block();

		InetSocketAddress address = server.address();
		RSocket socket = RSocketFactory.connect()
			.transport(TcpClientTransport.create(address.getHostName(), address.getPort()))
			.start()
			.block();

		assertThatCode(() -> socket
			.requestStream(DefaultPayload.create("Hello"))
			.map(Payload::getDataUtf8)
			.doOnNext(System.out::println)
			.take(10)
			.then()
			.doFinally(signalType -> socket.dispose())
			.then()
			.block())
		.isInstanceOf(RejectedSetupException.class);
	}
}
```

### PR DESCRIPTION
**Pull request by mostroverkhov**
RSocketRequester: fix concurrent modification of senders & receivers map on termination, closes #679, #695 

fix non-deterministic errors order on termination, closes #686

### CODE REVIEW

File: rsocket-core/src/main/java/io/rsocket/RSocketRequester.java [hunk 1]
```diff
@@ -614,4 +527,86 @@ private void handleMissingResponseProcessor(int streamId, FrameType type, ByteBu
...
+              });
+    }
+    senders.clear();
+    receivers.clear();
+    sendProcessor.dispose();
+    errorConsumer.accept(e);
+  }
+
+  private void removeStreamReceiver(int streamId) {
+    /*on termination senders & receivers are explicitly cleared to avoid removing from map while iterating over one
```
Comment (yschimke) [inline rsocket-core/src/main/java/io/rsocket/RSocketRequester.java]: why mention senders?

**Comment by yschimke** [comment]
Drive by review - I'll leave more thorough reviews to others.  Looks sensible enough.
